# -*- coding: utf-8 -*-
"""Codility_Iterations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGjQ3kXZyJ_M1hq85OA6WLC4Q4x473h-
"""

# factorial 만들기

n = int(input())

factorial = 1
for i in range(1, n+1):
  factorial *= i
print(factorial)

# 별 그리기



n = int(input())
for i in range(1, n+1):
  for j in range(i):
    print("*",end="")
  print()

# 별 그리기 (2)

n = int(input())

for i in range(n, 0, -1):
  for j in range(n-i):
    print(" ", end="")
  for j in range(2*i-1):
    print("*", end="")
  print()

# 자리수 구하기 (십진법)

n = int(input())

result = 0
while n>0:
  n = n//10
  result += 1

print(result)

# 피보나치 수열

n = int(input())
a = 0
b = 1

while a<=n:
  print(a, end=" ")
  c = a+b
  a = b
  b = c

# day

days = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]

for day in days:
  print(day)

# day - set(집합)

days = set(["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"])

for day in days:
  print(day)

# day - dic(딕셔너리)

days = {"Mo":"월", "Tu":"화", "We":"수", "Th":"목", "Fr":"금", "Sa":"토", "Su":"일"}

for day in days:
  print(day + "는 " + days[day])

